pipeline {
	agent any
	tools {
		maven 'maven_3.9.0'
		jdk 'java_17'
	}
	stages{
		stage ('build maven'){
			steps {
				checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: '09aa1ca0-6196-4967-83f9-6c55785becbb', url: 'https://github.com/jordanbonilla13/stripeUsers']])
				sh 'JAVA_HOME="/var/jenkins_home/tools/hudson.model.JDK/java_17/jdk-17.0.4.1"'
				sh 'mvn -f stripe/ clean install -DskipTests'
			}
		}
	}
}